---
title: "massSight combine iHMP and PRISM metabolites (IBD studies)"
output: html_document
date: "2023-07-07"
---


```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir ="~/Downloads/iHMP_PRISM")
```

```{r, eval = F, message = F}
#install.packages('devtools')
devtools::install_github("omicsEye/massSight", force = TRUE)
```



```{r, message = F}
library(massSight)
library(stringr)
library(readxl)
library(massSight)
library(ggplot2)
```


# read data 

iHMP: https://doi.org/10.1038/s41586-019-1237-9
data at:https://www.metabolomicsworkbench.org/data/DRCCStudySummary.php?Mode=SetupRawDataDownload&StudyID=ST000923
and
https://ibdmdb.org/tunnel/public/summary.html

iHMP has one excel file for all four methods (HULIC-pos, HILIC-neg, C18-neg, C8-pos)

PRISM: https://doi.org/10.1038/s41564-018-0306-4
data at:https://www.metabolomicsworkbench.org/data/DRCCStudySummary.php?Mode=SetupRawDataDownload&StudyID=ST001000

## Load iHMP data
```{r, cache = T, results = 'True', message=TRUE, warning=TRUE}

# list of recent annotations published by Broad Institute 
#iHMP_C18n <-
#  read_xlsx("data/iHMP/C18n_Metabolites_ID_AfterPublication_2021-05-17.xlsx")
#colnames(iHMP_C18n) <-
#  c("Method" , "Compound_ID" , "MZ"    , "RT" , "Metabolite")
#iHMP_C18n$Intensity <- 0

# iHMP published data
loaded_data <-
  massSight::load_data(
    input = 'HMP2_metabolomics.xlsx',
    type = 'all',
    sheet = 1,
    id = 'Compound_ID'
  )
loaded_data$feature_metadata$MZ <-
  as.numeric(loaded_data$feature_metadata$MZ)
loaded_data$feature_metadata$RT <-
  as.numeric(loaded_data$feature_metadata$RT)
feature_metadata2 <-
  loaded_data$feature_metadata[colnames(loaded_data$data), ]
feature_metadata2$Intensity <- colMeans(loaded_data$data, na.rm = T)
feature_metadata <- cbind(feature_metadata2, t(loaded_data$data))
ref_input <-
  feature_metadata2[!is.na(feature_metadata2$MZ) &
                      !is.na(feature_metadata2$RT),] 
#ids <- sapply(str_split(feature_metadata2$Compound_ID, "_"), "[[", 2)
#feature_metadata3 <- cbind(feature_metadata2, #t(loaded_data))
#c("Compound_ID", "MZ", "RT", "Intensity", "Metabolite")
```


## load PRISM clustered data as main output 
```{r, cache = T, results = 'True', message=TRUE, warning=TRUE}

PRISM <-
  massSight::load_data(
    input = '41564_2018_306_MOESM_combined3_4_ESM.xlsx',
    type = 'all',
    sheet = 1,
    id = 'Compound_ID'
  )
PRISM$feature_metadata$MZ <-
  as.numeric(PRISM$feature_metadata$MZ)
PRISM$feature_metadata$RT <-
  as.numeric(PRISM$feature_metadata$RT)
feature_metadata2 <-
  PRISM$feature_metadata[colnames(PRISM$data), ]
feature_metadata2$Intensity <- colMeans(PRISM$data, na.rm = T)
feature_metadata <- cbind(feature_metadata2, t(PRISM$data))
PRISM_input <-
  feature_metadata2[!is.na(feature_metadata2$MZ) &
                      !is.na(feature_metadata2$RT),] 
PRISM_Methods <- sapply(str_split(PRISM_input$Compound_ID, "_"), "[[", 1)
PRISM_input$Method <- PRISM_Methods
```
# Approach 1: iHMP vs. PRISM method by method


## Create an object for iHMP data as reference for alignment and combining 

```{r, cache = T, results = 'hide', message=TRUE, warning=TRUE}
aligned_df <- vector(mode = "list", length = 4)
profiling_methods = c("HILIC-neg", "HILIC-pos" , "C18-neg", "C8-pos")
names(aligned_df) <- profiling_methods
ref = query = final_smooth = aligned_df
for (profiling_method in profiling_methods){
  
  ref[[profiling_method]] <-
    create_ms_obj(
      df = ref_input[ref_input$Method==profiling_method,],
      name = "iHMP",
      id_name = "Compound_ID",
      rt_name = "RT",
      mz_name = "MZ",
      int_name = "Intensity"
    )
  
  query[[profiling_method]] <-
    create_ms_obj(
      df = PRISM_input[PRISM_input$Method==profiling_method,],
      name = "PRISM",
      id_name = "Compound_ID",
      rt_name = "RT",
      mz_name = "MZ",
      int_name = "Intensity"
    )
  
  # create and save distribution of MZ and RT of features
    ms1_distr <- massSight::distribution_plot(query[[profiling_method]])
    ms2_distr <- massSight::distribution_plot(ref[[profiling_method]])
    ggsave(
      filename = paste0('analysis/iHMP_PRISM/PRISM_', profiling_method,'_query_distr_plot.png'),
      plot = ms1_distr,
      width = 5,
      height = 5,
      units = "in",
      dpi = 300
    )
    ggsave(
      filename = paste0('analysis/iHMP_PRISM/iHMP_', profiling_method, '_ref_distr_plot.png'),
      plot = ms2_distr,
      width = 5,
      height = 5,
      units = "in",
      dpi = 300
    )
    print(ms1_distr)
    print(ms2_distr)
}
```

```{r, cache = T, results = 'hide', message=TRUE, warning=TRUE}
for (profiling_method in profiling_methods){
  print(profiling_method)
  aligned_df[[profiling_method]] <-
    auto_combine(ref[[profiling_method]], query[[profiling_method]], smooth_method = "gam", log = NULL)
}
```

# View and write
```{r, cache = T, results = 'hide', message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir ="~/Dropbox/Ali-Docs/Research_docs/Projects/PragmaBio/")
for (profiling_method in profiling_methods){
#View(aligned_df@all_matched[[profiling_method]])
  write.table(aligned_df[[profiling_method]]@all_matched, file=paste0('analysis/iHMP_PRISM/iHMP_PRISM_', profiling_method, '_excel.tsv'), quote=FALSE, sep='\t', row.names=FALSE)
}
```

# Visualization

```{r, cache = T, results = 'hide', message=FALSE, warning=FALSE}
for (profiling_method in profiling_methods){
  final_smooth[[profiling_method]] <- final_plots(aligned_df[[profiling_method]])
  print(final_smooth[[profiling_method]])  
  ggsave(
    filename = paste0('analysis/iHMP_PRISM/iHMP_vs_all_PRISM_excel_', profiling_method, '_massSight_plots.png'),
    plot = final_smooth[[profiling_method]],
    width = 5,
    height = 5,
    units = "in",
    dpi = 300
  )
}
```
```{r, cache = T, results = 'hide', message=FALSE, warning=FALSE}
#View(temp_aligned@all_matched)
for (profiling_method in profiling_methods){
  write.table(aligned_df[[profiling_method]]@all_matched, file=paste0('analysis/iHMP_PRISM/iHMP_PRISM_', profiling_method, '_excel.tsv'),
              quote=FALSE, sep='\t', row.names=FALSE)
}
```
